[package]
name = "xee-extract-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["full", "visit"] }
proc-macro2 = "1.0"
quote = "1.0"
proc-macro-error = "1.0"
xot = "0.31.2" 